apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: opentelemetry-operator-system
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ead-api-metrics
  namespace: opentelemetry-operator-system
spec:
  mode: deployment

  serviceAccount: adot-collector

  config:
    extensions:
      sigv4auth:
        region: us-east-2
        service: aps

    # where metrics come from
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: ead-api
              scrape_interval: 30s
              scheme: http
              metrics_path: /metrics

              static_configs:
                - targets:
                    - ead-api.default.svc.cluster.local:80

    # where metrics go
    exporters:
      prometheusremotewrite:
        endpoint: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/<AMP_WORKSPACE_ID>/api/v1/remote_write
        auth:
          authenticator: sigv4auth

    # connects receiver -> exporter
    service:
      extensions:
        - sigv4auth

      pipelines:
        metrics:
          receivers:
            - prometheus
          exporters:
            - prometheusremotewrite