apiVersion: apps/v1
kind: Deployment

metadata:
  name: ead-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ead-api

  template:
    metadata:
      labels:
        app: ead-api

    spec:
      containers:
        - name: ead-api

          image: account.dkr.ecr.us-east-2.amazonaws.com/ead-api:IMAGE_TAG

          ports:
            - containerPort: 3000