apiVersion: apps/v1
kind: Deployment

metadata:
  name: ead-api
  namespace: ead-api

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1    

  selector:
    matchLabels:
      app: ead-api

  template:
    metadata:
      labels:
        app: ead-api
        app.kubernetes.io/name: ead-api
        app.kubernetes.io/component: ead-api
        app.kubernetes.io/part-of: ead

    spec:
      serviceAccount: ead-api

      containers:
        - name: ead-api

          image: account.dkr.ecr.us-east-2.amazonaws.com/ead/ead-api:IMAGE_TAG

          envFrom:
            - secretRef:
                name: ead-api-secret
            
            - configMapRef:
                name: ead-api-config

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"