name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24] # allows to test against multiple Node.js versions if needed

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v6 # uploads artifact to repo's actions section
        with:
          name: application-build
          path: dist