name: Docker

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  resolve-environment:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    outputs:
      environment: ${{ steps.env.outputs.environment }}

    steps:
      - name: Resolve Environment
        id: env
        run: |
          BRANCH=${{ github.event.workflow_run.head_branch }}

          if [ "$BRANCH" = "development" ]; then
            echo "environment=development" >> "$GITHUB_OUTPUT"
          elif [ "$BRANCH" = "staging" ]; then
            echo "environment=staging" >> "$GITHUB_OUTPUT"
          elif [ "$BRANCH" = "main" ]; then
            echo "environment=production" >> "$GITHUB_OUTPUT"
          else
            echo "Unsupported deployment branch: $BRANCH"
            exit 1
          fi

  build-and-push:
    needs: resolve-environment
    runs-on: ubuntu-latest

    environment: ${{ needs.resolve-environment.outputs.environment }}
    
    steps:
      - name: Environment Check
        run: echo env= ${{ needs.resolve-environment.outputs.environment }}

      - name: Checkout Source
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ead-api:${{ github.event.workflow_run.head_sha }} \
            -t ead-api:latest \
            .

      - name: Tag Docker Image
        run: |
          IMAGE_REPOSITORY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"

          docker tag ead-api:${{ github.event.workflow_run.head_sha }} "$IMAGE_REPOSITORY:${{ github.event.workflow_run.head_sha }}"
          docker tag ead-api:latest "$IMAGE_REPOSITORY:latest"

      - name: Push Docker Image
        run: |
          IMAGE_REPOSITORY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"

          docker push "$IMAGE_REPOSITORY:${{ github.event.workflow_run.head_sha }}"
          docker push "$IMAGE_REPOSITORY:latest"