name: Docker

on:
  push:
    branches:
      - development
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: development

    permissions:
      contents: read
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Data Check Test
        run: echo "aws-region - ${{ secrets.AWS_REGION }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t ead-api:${{ github.sha }} \
            -t ead-api:latest \
            .

      - name: Tag Docker Image
        run: |
          docker tag \
            ead-api:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ead/ead-api:${{ github.sha }} \
            ead-api:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ead/ead-api:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ead/ead-api:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ead/ead-api:latest
