name: Terraform

on:
  workflow_dispatch: # TODO: add to the pipelines flow
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production
      action:
        description: "Terraform action"
        required: true
        default: "plan" # TODO: switch to apply once plan works
        type: choice
        options:
          - plan
          - apply

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ inputs.environment }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ../../

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan